"""initial schema

Revision ID: 57a71b5051bf
Revises: 
Create Date: 2026-06-10 02:12:20.525277
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57a71b5051bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_risk_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('mitre_techniques', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index('ix_incidents_last_seen', ['last_seen'], unique=False)
        batch_op.create_index('ix_incidents_source_ip', ['source_ip'], unique=False)
        batch_op.create_index('ix_incidents_status', ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('attacks',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=False),
    sa.Column('source_port', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('asn', sa.String(length=32), nullable=True),
    sa.Column('isp', sa.String(length=128), nullable=True),
    sa.Column('reputation', sa.Integer(), nullable=True),
    sa.Column('is_malicious', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('ssh_version', sa.String(length=128), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('auth_attempts', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('behaviors', sa.Text(), nullable=True),
    sa.Column('mitre_techniques', sa.Text(), nullable=True),
    sa.Column('incident_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_attacks_incident_id_incidents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attacks'))
    )
    with op.batch_alter_table('attacks', schema=None) as batch_op:
        batch_op.create_index('ix_attacks_country', ['country'], unique=False)
        batch_op.create_index('ix_attacks_incident_id', ['incident_id'], unique=False)
        batch_op.create_index('ix_attacks_ip_time', ['source_ip', 'timestamp'], unique=False)
        batch_op.create_index('ix_attacks_password', ['password'], unique=False)
        batch_op.create_index('ix_attacks_risk_score', ['risk_score'], unique=False)
        batch_op.create_index('ix_attacks_session_id', ['session_id'], unique=False)
        batch_op.create_index('ix_attacks_source_ip', ['source_ip'], unique=False)
        batch_op.create_index('ix_attacks_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('ix_attacks_username', ['username'], unique=False)

    op.create_table('commands',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('attack_id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('command_type', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['attack_id'], ['attacks.id'], name=op.f('fk_commands_attack_id_attacks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commands'))
    )
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.create_index('ix_commands_attack_id', ['attack_id'], unique=False)
        batch_op.create_index('ix_commands_session_id', ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.drop_index('ix_commands_session_id')
        batch_op.drop_index('ix_commands_attack_id')

    op.drop_table('commands')
    with op.batch_alter_table('attacks', schema=None) as batch_op:
        batch_op.drop_index('ix_attacks_username')
        batch_op.drop_index('ix_attacks_timestamp')
        batch_op.drop_index('ix_attacks_source_ip')
        batch_op.drop_index('ix_attacks_session_id')
        batch_op.drop_index('ix_attacks_risk_score')
        batch_op.drop_index('ix_attacks_password')
        batch_op.drop_index('ix_attacks_ip_time')
        batch_op.drop_index('ix_attacks_incident_id')
        batch_op.drop_index('ix_attacks_country')

    op.drop_table('attacks')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index('ix_incidents_status')
        batch_op.drop_index('ix_incidents_source_ip')
        batch_op.drop_index('ix_incidents_last_seen')

    op.drop_table('incidents')
    # ### end Alembic commands ###
